# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master
- develop
- releases/*
- features/*

pool:
  vmImage: 'macOS 10.13'

variables:
  scheme: 'TwitchApp'
  sdk: 'iphoneos'
  configuration: 'Debug'
       
steps:
# - script: /usr/local/bin/carthage update --platform ios
#   displayName: 'Carthage installation'
- script: |
    CALL gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle
  displayName: 'Execute Bundle'

- script: gem install slather
  displayName: 'Install Slather'  

#slather setup TwitchApp.xcodeproj
- script: slather setup TwitchApp.xcodeproj
  displayName: 'Setup Slather'  

- task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'clean build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: '10'
    packageApp: false
    xcWorkspacePath: 'TwitchApp.xcodeproj'
    useXcpretty: true

- task: Xcode@5
  displayName: 'Running XCTest' #/XCUITest
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    # configuration: '$(configuration)'
    xcodeVersion: '10'
    # packageApp: false
    xcWorkspacePath: 'TwitchApp.xcodeproj'
    destinationSimulators: 'iPhone 7'
    # destinationTypeOption: 'simulators'
    # destinationPlatformOption: 'iOS'
    # signingOption: "auto"
    useXcpretty: true

- script: xcodebuild -project TwitchApp.xcodeproj -scheme TwitchApp -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 7' -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -r "html" -o "Report/tests.html"
  displayName: 'Test'

#bash <(curl https://codecov.io/bash) -t $(CODECOV_TOKEN)
- script: bash <(curl https://codecov.io/bash) -t f1b873d7-af79-480a-afbc-5310cf4ba484
  displayName: 'Upload coverage to Codecov'    

# - script: slather coverage -x --output-directory Report/slather/xml_report --scheme TwitchApp  TwitchApp.xcodeproj
#   displayName: 'Run Slather'

# - script: slather coverage -s --scheme TwitchApp TwitchApp.xcodeproj
#   displayName: 'Run Slather scheme TwitchApp'