# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master
- develop
- releases/*
- features/*

pr:
- master
- develop
- releases/*
- features/*

pool:
  vmImage: 'macOS 10.13'

variables:
  scheme: 'TwitchApp'
  sdk: 'iphoneos'
  configuration: 'Debug'

jobs:
- job: Setup
  steps:
  - script: gem install bundler
  displayName: 'Install bundler'

  - script: bundle install
  displayName: 'Bundle Install'

  - script: bundle
    displayName: 'Execute Bundle'

  - script: gem install slather
    displayName: 'Install Slather'  

- job: Clean-Build
  dependsOn: Setup
  condition: succeeded('Setup')
  steps:
  - task: Xcode@5
  displayName: 'Xcode debug build'
  inputs:
    actions: 'clean build'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: '10'
    packageApp: false
    xcWorkspacePath: 'TwitchApp.xcodeproj'
    useXcpretty: true

- job: Test
  dependsOn:
  - Setup
  - Clean-Build
  condition: succeeded('Clean-Build')
  steps:
  - task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: '$(configuration)'
    xcodeVersion: '10'
    packageApp: false
    xcWorkspacePath: 'TwitchApp.xcodeproj'
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true

- job: Coverage
  dependsOn:
  - Setup
  - Clean-Build
  - Test
  condition: succeeded('Test')
  steps:
  - script: slather coverage -x --output-directory Report/slather/xml_report --scheme TwitchApp  TwitchApp.xcodeproj
  displayName: 'Run Slather'

  - script: bash <(curl https://codecov.io/bash) -t $(CODECOV_TOKEN) -f Report/slather/xml_report -F adder -F subtractor
    displayName: 'Upload coverage to codecov.io'